# Generated by Django 3.2.6 on 2021-08-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_farmer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.farmer')),
            ],
        ),
    ]
