# Generated by Django 3.2.6 on 2021-08-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='area',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
    ]
